# Qualitative Data Analysis

> Since the open-ended responses are relatively small, the approach is manual thematic analysis assisted by Python. The goal is to transform open-ended responses into: themes, categories and actionable requirement revisions.

In [1]:
import pandas as pd

df = pd.read_csv("datasets/qualitative_data.csv")
df.head()

,respondent_id,role_group,experience_raw,familiarity_raw,unnecessary_requirements,improvement_suggestions,missing_features,comments,approval,response_quality
0,R01,faculty,3-5 years,Very familiar,involving HTE as a role in your internship sys...,Clarify the document management and how its go...,Mentor check-in that will auto generate a goog...,"Make the system be capable of audits, reports ...",approved_revision,substantive_feedback
1,R02,ojt_coordinator,10+ years,Familiar,none,none,For consideration on the automated communicati...,so far we only have the requirements for asses...,approved,substantive_feedback
2,R03,faculty,3-5 years,Familiar,none,"The requirements are clear overall. However, i...",Yes. The system could include:\n\n1. Email or ...,The system should have a simple and user-frien...,approved_revision,substantive_feedback
3,R04,faculty,3-5 years,Very familiar,none,User access and credentials especially for HTE,Documentation feature,none,approved,substantive_feedback
4,R05,faculty,0-2 years,Familiar,missing,missing,missing,missing,approved,partial_feedback

In [2]:
# validate qualitative data
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 10 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   respondent_id             11 non-null     str
 1   role_group                11 non-null     str
 2   experience_raw            11 non-null     str
 3   familiarity_raw           11 non-null     str
 4   unnecessary_requirements  11 non-null     str
 5   improvement_suggestions   11 non-null     str
 6   missing_features          11 non-null     str
 7   comments                  11 non-null     str
 8   approval                  11 non-null     str
 9   response_quality          11 non-null     str
dtypes: str(10)
memory usage: 1012.0 bytes

In [3]:
df.isnull().sum()

respondent_id               0
role_group                  0
experience_raw              0
familiarity_raw             0
unnecessary_requirements    0
improvement_suggestions     0
missing_features            0
comments                    0
approval                    0
response_quality            0
dtype: int64

In [4]:
# Separate substantive responses
ignore_values = ['none', 'missing', 'insufficient_context']

### Analyze each open-ended question separately

In [5]:
# Unnecessary Requirements
# Which requirements are unnecessary?
valid_unnecessary = df[
    ~df['unnecessary_requirements'].isin(ignore_values)
]['unnecessary_requirements']

print(valid_unnecessary.tolist())

['involving HTE as a role in your internship system should be unnecessary since it may violate their IT policies with websites. Now what you can do with that is incorporate paper data with the digital data to ensure there is a paper trail for auditing. Then for evaluations, the system can just generate a link for them to do the evaluations securely. That can be pre-arranged with the HTE. I know its counter-intuitive with the reasons of not assigning an HTE role into the system but this magic link with the evaluation is just a one time thing for the HTE and does not disrupt their day to day operations.', 'Student Management: no need to build this within IMS, integrate IMS with CAMU instead for student profiles. It should simply read this data via an API or single sign-on (SSO) token, maintaining only an associative internship state for that student. Internship Status Tracking is a subset of Internship Management. Authentication & RBAC can be merged', 'Attendance Management may be redundant if internship hours are already tracked through status updates and evaluation.\nDuplicate listing of Security, Reliability, Usability, and Compliance in the non-functional section should be consolidated for clarity.']

Emerging themes:
HTE role may be unnecessary / limited access
Student management may be integrated with CAMU
Attendance management redundancy
Duplicate functional/non-functional requirements

Possible theme categories:

scope_reduction
redundancy
external_integration

In [6]:
# Improvement Suggestions
valid_improvements = df[
    ~df['improvement_suggestions'].isin(ignore_values)
]['improvement_suggestions']

print(valid_improvements.tolist())

['Clarify the document management and how its gonna be used in the system as part of audit. Also, the attendance validation and verification should be made clear as to how to verify it.', 'The requirements are clear overall. However, it would be helpful to add more details about user roles, internship status updates, and reporting to avoid confusion during development.', 'User access and credentials especially for HTE', 'Clarify authentication by specifying how users will log in, recover passwords, and manage sessions. Role Management should also be detailed by identifying the exact users, such as admin, coordinator, student, and HTE supervisor, and defining what each role is allowed to access or modify. Internship Management needs the most clarification because it is too broad. Improve Attendance Management by explaining how time logs are submitted, approved, corrected, and computed. Security should include specific controls such as role-based access, secure file storage, and data protection. Reliability should mention backups, data recovery, and data accuracy. Usability should clarify that the system must be simple, accessible, and easy to navigate. Compliance should specify the CHED or institutional internship requirements, reports, and records that the system must support.', 'Document Management: clarify whether this includes version control and digital signatures.\nReporting: specify if customizable dashboards and export formats (PDF, Excel) are supported.\nNotifications: define channels (email, SMS, in-app) and escalation rules.', 'stability of the system in relation to possible hacking and leakage of information which may disrupt all the data stored within the system']

Likely themes:

* Authentication clarification
* Role clarification
* Attendance validation
* Security enhancement
* Reporting clarification
* Document management workflow

In [7]:
# Missing features
valid_missing = df[
    ~df['missing_features'].isin(ignore_values)
]['missing_features']

print(valid_missing.tolist())

["Mentor check-in that will auto generate a google meet link once a checkin was scheduled. Mentor/Adviser's approval must be required to generate the google meet link and is automatically added to the mentor's calendar.", 'For consideration on the automated communication with HTEs, Interns, Advisers, Coordinators everytime there will be changes with the status of the interns progress. Example is auto generation of email that will be sent to HTEs as indicated in a schedule for release where HTEs will be able to comply immediately and can be reminded if they are not able to submit it on certain due dates.', 'Yes. The system could include:\n\n1. Email or SMS notifications for important updates.\n2. A dashboard for students, coordinators, and HTEs.\n3. Calendar or schedule management for internship activities.\n4. Feedback or messaging between students and supervisors.', 'Documentation feature ', 'Consider including internship application and approval management, where students can apply for available internship opportunities and coordinators or HTE supervisors can approve, reject, or shortlist applications. Add notification and reminder features to inform users about pending approvals, missing documents, attendance deadlines, evaluation schedules, and internship completion requirements. Internship posting or opportunity management, where HTEs or coordinators can post available internship slots, job descriptions, qualifications, schedules, and required skills. include supervisor assignment and monitoring, allowing coordinators to assign HTE supervisors or faculty advisers to students and monitor their progress throughout the internship period. consider adding document approval workflow, not just document upload. This means documents can be marked as pending, approved, rejected, or needing resubmission. Another missing feature is certificate or completion clearance generation, where the system can verify attendance hours, documents, and evaluations before marking a student as completed. Add a Dashboard feature would be useful for students, coordinators, administrators, and HTEs. It can show quick summaries such as number of assigned interns, pending documents, completed hours, ongoing internships, and evaluation status.', 'Integration with existing LMS or ERP systems for seamless data flow. Mobile accessibility for students and supervisors. Analytics for internship outcomes (completion rates, performance trends).', 'Last updates made by user such notifications. Level of access of user']

Likely themes:

* Notifications
* Dashboard
* LMS integration
* Analytics
* Document approval workflow
* Certificate generation
* Communication automation
* Mobile accessibility

In [8]:
# Comments
valid_comments = df[
    ~df['comments'].isin(ignore_values)
]['comments']

print(valid_comments.tolist())

['Make the system be capable of audits, reports and at the same time be easier for students to manage their internship stuff without going out of the web app. \np.s., I have made a same system in our university once and was then adopted and now improved, you can ask me about it. :)', 'so far we only have the requirements for assessment in relation to the system design. For now we can just align this with the feature suggestion above.', 'The system should have a simple and user-friendly design, work well on both computers and mobile devices, and ensure that student data is secure and regularly backed up.', 'I hope the design is minimalist and easy to follow.', 'Prioritize scalability so the system can expand to multiple campuses. Strong emphasis on security and audit logging is commendable.']

Themes:

* Security
* Scalability
* Audit support
* Usability
* Minimalist design

In [9]:
# Step 1 — Remove low-quality responses
valid_df = df[
    ~df["response_quality"].isin(["insufficient_context"])
].copy()

print(valid_df[["respondent_id", "role_group", "response_quality"]])

   respondent_id       role_group      response_quality
0            R01          faculty  substantive_feedback
1            R02  ojt_coordinator  substantive_feedback
2            R03          faculty  substantive_feedback
3            R04          faculty  substantive_feedback
4            R05          faculty      partial_feedback
5            R06          faculty      partial_feedback
6            R07  ojt_coordinator  substantive_feedback
8            R09          faculty  substantive_feedback
9            R10   hte_supervisor  substantive_feedback
10           R11   hte_supervisor  substantive_feedback

In [10]:
df[['respondent_id','role_group','improvement_suggestions','missing_features','comments']]

,respondent_id,role_group,improvement_suggestions,missing_features,comments
0,R01,faculty,Clarify the document management and how its go...,Mentor check-in that will auto generate a goog...,"Make the system be capable of audits, reports ..."
1,R02,ojt_coordinator,none,For consideration on the automated communicati...,so far we only have the requirements for asses...
2,R03,faculty,"The requirements are clear overall. However, i...",Yes. The system could include:\n\n1. Email or ...,The system should have a simple and user-frien...
3,R04,faculty,User access and credentials especially for HTE,Documentation feature,none
4,R05,faculty,missing,missing,missing
5,R06,faculty,none,none,I hope the design is minimalist and easy to fo...
6,R07,ojt_coordinator,Clarify authentication by specifying how users...,Consider including internship application and ...,missing
7,R08,faculty,insufficient_context,insufficient_context,insufficient_context
8,R09,faculty,Document Management: clarify whether this incl...,Integration with existing LMS or ERP systems f...,Prioritize scalability so the system can expan...
9,R10,hte_supervisor,stability of the system in relation to possibl...,missing,missing
10,R11,hte_supervisor,missing,Last updates made by user such notifications. ...,missing

In [11]:
text_cols = [
    'unnecessary_requirements',
    'improvement_suggestions',
    'missing_features',
    'comments'
]

df['combined_feedback'] = df[text_cols].fillna('').agg(' '.join, axis=1)

In [12]:
# Keep Only Meaningful Responses
coding_df = df[
    df["response_quality"] != "insufficient_context"
].copy()

coding_df[["respondent_id","response_quality"]]

   respondent_id      response_quality
0            R01  substantive_feedback
1            R02  substantive_feedback
2            R03  substantive_feedback
3            R04  substantive_feedback
4            R05      partial_feedback
5            R06      partial_feedback
6            R07  substantive_feedback
8            R09  substantive_feedback
9            R10  substantive_feedback
10           R11  substantive_feedback

In [13]:
# Keep Only Meaningful Responses
qual = df[
    df["response_quality"] != "insufficient_context"
].copy()

print("Number of substantive responses:", len(qual))

Number of substantive responses: 10

In [14]:
# Merge the Four Open-ended Questions
# Instead of coding four columns separately, treat each respondent's comments as one transcript.
text_cols = [
    "unnecessary_requirements",
    "improvement_suggestions",
    "missing_features",
    "comments"
]

qual["full_response"] = (
    qual[text_cols]
    .fillna("")
    .agg(" ".join, axis=1)
)

qual[["respondent_id","full_response"]]

   respondent_id                                      full_response
0            R01  involving HTE as a role in your internship sys...
1            R02  none none For consideration on the automated c...
2            R03  none The requirements are clear overall. Howev...
3            R04  none User access and credentials especially fo...
4            R05                    missing missing missing missing
5            R06  none none none I hope the design is minimalist...
6            R07  Student Management: no need to build this with...
8            R09  Attendance Management may be redundant if inte...
9            R10  none stability of the system in relation to po...
10           R11  missing missing Last updates made by user such...

In [15]:
# Display One Response at a Time
for _, row in qual.iterrows():
    print("="*80)
    print(row["respondent_id"])
    print()
    print(row["full_response"])
    print()

================================================================================
R01

involving HTE as a role in your internship system should be unnecessary since it may violate their IT policies with websites. Now what you can do with that is incorporate paper data with the digital data to ensure there is a paper trail for auditing. Then for evaluations, the system can just generate a link for them to do the evaluations securely. That can be pre-arranged with the HTE. I know its counter-intuitive with the reasons of not assigning an HTE role into the system but this magic link with the evaluation is just a one time thing for the HTE and does not disrupt their day to day operations. Clarify the document management and how its gonna be used in the system as part of audit. Also, the attendance validation and verification should be made clear as to how to verify it. Mentor check-in that will auto generate a google meet link once a checkin was scheduled. Mentor/Adviser's approval must be required to generate the google meet link and is automatically added to the mentor's calendar. Make the system be capable of audits, reports and at the same time be easier for students to manage their internship stuff without going out of the web app.
p.s., I have made a same system in our university once and was then adopted and now improved, you can ask me about it. :)

================================================================================
R02

none none For consideration on the automated communication with HTEs, Interns, Advisers, Coordinators everytime there will be changes with the status of the interns progress. Example is auto generation of email that will be sent to HTEs as indicated in a schedule for release where HTEs will be able to comply immediately and can be reminded if they are not able to submit it on certain due dates. so far we only have the requirements for assessment in relation to the system design. For now we can just align this with the feature suggestion above.

================================================================================
R03

none The requirements are clear overall. However, it would be helpful to add more details about user roles, internship status updates, and reporting to avoid confusion during development. Yes. The system could include:

1. Email or SMS notifications for important updates.
2. A dashboard for students, coordinators, and HTEs.
3. Calendar or schedule management for internship activities.
4. Feedback or messaging between students and supervisors. The system should have a simple and user-friendly design, work well on both computers and mobile devices, and ensure that student data is secure and regularly backed up.

================================================================================
R04

none User access and credentials especially for HTE Documentation feature  none

================================================================================
R05

missing missing missing missing

================================================================================
R06

none none none I hope the design is minimalist and easy to follow.

================================================================================
R07

Student Management: no need to build this within IMS, integrate IMS with CAMU instead for student profiles. It should simply read this data via an API or single sign-on (SSO) token, maintaining only an associative internship state for that student. Internship Status Tracking is a subset of Internship Management. Authentication & RBAC can be merged Clarify authentication by specifying how users will log in, recover passwords, and manage sessions. Role Management should also be detailed by identifying the exact users, such as admin, coordinator, student, and HTE supervisor, and defining what each role is allowed to access or modify. Internship Management needs the most clarification because it is too broad. Improve Attendance Management by explaining how time logs are submitted, approved, corrected, and computed. Security should include specific controls such as role-based access, secure file storage, and data protection. Reliability should mention backups, data recovery, and data accuracy. Usability should clarify that the system must be simple, accessible, and easy to navigate. Compliance should specify the CHED or institutional internship requirements, reports, and records that the system must support. Consider including internship application and approval management, where students can apply for available internship opportunities and coordinators or HTE supervisors can approve, reject, or shortlist applications. Add notification and reminder features to inform users about pending approvals, missing documents, attendance deadlines, evaluation schedules, and internship completion requirements. Internship posting or opportunity management, where HTEs or coordinators can post available internship slots, job descriptions, qualifications, schedules, and required skills. include supervisor assignment and monitoring, allowing coordinators to assign HTE supervisors or faculty advisers to students and monitor their progress throughout the internship period. consider adding document approval workflow, not just document upload. This means documents can be marked as pending, approved, rejected, or needing resubmission. Another missing feature is certificate or completion clearance generation, where the system can verify attendance hours, documents, and evaluations before marking a student as completed. Add a Dashboard feature would be useful for students, coordinators, administrators, and HTEs. It can show quick summaries such as number of assigned interns, pending documents, completed hours, ongoing internships, and evaluation status. missing

================================================================================
R09

Attendance Management may be redundant if internship hours are already tracked through status updates and evaluation.
Duplicate listing of Security, Reliability, Usability, and Compliance in the non-functional section should be consolidated for clarity. Document Management: clarify whether this includes version control and digital signatures.
Reporting: specify if customizable dashboards and export formats (PDF, Excel) are supported.
Notifications: define channels (email, SMS, in-app) and escalation rules. Integration with existing LMS or ERP systems for seamless data flow. Mobile accessibility for students and supervisors. Analytics for internship outcomes (completion rates, performance trends). Prioritize scalability so the system can expand to multiple campuses. Strong emphasis on security and audit logging is commendable.

================================================================================
R10

none stability of the system in relation to possible hacking and leakage of information which may disrupt all the data stored within the system missing missing

================================================================================
R11

missing missing Last updates made by user such notifications. Level of access of user missing

In [16]:
# Open Coding Table

codes = {

    "R01":[
        "HTE Role Simplification",
        "Audit Trail Support",
        "Attendance Verification",
        "External Evaluation Process",
        "Mentor Coordination"
    ],

    "R02":[
        "Notification Support",
        "Automated Notifications",
        "Reminder System"
    ],

    "R03":[
        "Role Definition",
        "Status Tracking Clarification",
        "Notification Support",
        "Dashboard",
        "Calendar Management",
        "Messaging",
        "Mobile Accessibility",
        "Data Backup"
    ],

    "R04":[
        "HTE Access Control",
        "Role Definition",
        "Document Management"
    ],

    "R05":[
        "No Actionable Feedback"
    ],

    "R06":[
        "Minimalist User Interface"
    ],

    "R07":[
        "Student Information Integration",
        "Authentication Clarification",
        "Role Definition",
        "Attendance Workflow",
        "Security Controls",
        "Reliability Requirements",
        "Usability Clarification",
        "Compliance Clarification",
        "Application Workflow",
        "Notification Support",
        "Internship Opportunity Management",
        "Supervisor Assignment",
        "Document Approval Workflow",
        "Certificate Generation",
        "Dashboard"
    ],

    "R09":[
        "Requirement Consolidation",
        "Document Version Control",
        "Digital Signature",
        "Customizable Reporting",
        "Notification Support",
        "System Integration",
        "Mobile Accessibility",
        "Analytics",
        "Scalability",
        "Audit Logging"
    ],

    "R10":[
        "System Security",
        "Data Protection"
    ],

    "R11":[
        "Activity Notifications",
        "Role-Based Access"
    ]
}

In [17]:
# Convert to DF to create the open code table
coding_table = []

for respondent, code_list in codes.items():

    for code in code_list:

        coding_table.append({
            "Respondent": respondent,
            "Open Code": code
        })

coding_df = pd.DataFrame(coding_table)

coding_df

   Respondent                          Open Code
0         R01            HTE Role Simplification
1         R01                Audit Trail Support
2         R01            Attendance Verification
3         R01        External Evaluation Process
4         R01                Mentor Coordination
5         R02               Notification Support
6         R02            Automated Notifications
7         R02                    Reminder System
8         R03                    Role Definition
9         R03      Status Tracking Clarification
10        R03               Notification Support
11        R03                          Dashboard
12        R03                Calendar Management
13        R03                          Messaging
14        R03               Mobile Accessibility
15        R03                        Data Backup
16        R04                 HTE Access Control
17        R04                    Role Definition
18        R04                Document Management
19        R05             No Actionable Feedback
20        R06          Minimalist User Interface
21        R07    Student Information Integration
22        R07       Authentication Clarification
23        R07                    Role Definition
24        R07                Attendance Workflow
25        R07                  Security Controls
26        R07           Reliability Requirements
27        R07            Usability Clarification
28        R07           Compliance Clarification
29        R07               Application Workflow
30        R07               Notification Support
31        R07  Internship Opportunity Management
32        R07              Supervisor Assignment
33        R07         Document Approval Workflow
34        R07             Certificate Generation
35        R07                          Dashboard
36        R09          Requirement Consolidation
37        R09           Document Version Control
38        R09                  Digital Signature
39        R09             Customizable Reporting
40        R09               Notification Support
41        R09                 System Integration
42        R09               Mobile Accessibility
43        R09                          Analytics
44        R09                        Scalability
45        R09                      Audit Logging
46        R10                    System Security
47        R10                    Data Protection
48        R11             Activity Notifications
49        R11                  Role-Based Access

In [18]:
# Count Code Frequencies
code_frequency = (
    coding_df
    .value_counts("Open Code")
    .reset_index(name="Frequency")
    .sort_values("Frequency", ascending=False)
)

code_frequency

                            Open Code  Frequency
0                Notification Support          4
1                     Role Definition          3
2                           Dashboard          2
3                Mobile Accessibility          2
4             HTE Role Simplification          1
5                 Audit Trail Support          1
6             Attendance Verification          1
7         External Evaluation Process          1
8                 Mentor Coordination          1
9             Automated Notifications          1
10                    Reminder System          1
11      Status Tracking Clarification          1
12                Calendar Management          1
13                          Messaging          1
14                        Data Backup          1
15                 HTE Access Control          1
16                Document Management          1
17             No Actionable Feedback          1
18          Minimalist User Interface          1
19    Student Information Integration          1
20       Authentication Clarification          1
21                Attendance Workflow          1
22                  Security Controls          1
23           Reliability Requirements          1
24            Usability Clarification          1
25           Compliance Clarification          1
26               Application Workflow          1
27  Internship Opportunity Management          1
28              Supervisor Assignment          1
29         Document Approval Workflow          1
30             Certificate Generation          1
31          Requirement Consolidation          1
32           Document Version Control          1
33                  Digital Signature          1
34             Customizable Reporting          1
35                 System Integration          1
36                          Analytics          1
37                        Scalability          1
38                      Audit Logging          1
39                    System Security          1
40                    Data Protection          1
41             Activity Notifications          1
42                  Role-Based Access          1